org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=viscript_team
mod_name=ViScriptTeam
mod_license=GNU LGPL 3.0
mod_version=1.0.2 beta
mod_group_id=com.zhenshiz
mod_authors=zhenshiz
mod_description=description

ldlib2_version=2.2.32
viscriptlib_version=1.1.6.2

kubejs_version = 2101.7.2-build.368
rhino_version = 2101.2.7-build.81

iris_version=1.8.12+1.21.1-neoforge
sodium_version=mc1.21.1-0.6.13-neoforge
lsp_version=1.13.2
jei_version=NMhqixRu
